name: Build

on:
  push:
    branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install --assume-yes nasm
    - name: Run build script
      run: bash ./build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        path: ./haiku-cross.tar.xz